theme: jekyll-theme-minimal
title: Andrés F. López-Lopera
description:
  Postdoctoral researcher <br>
  M2CI-DTIS, ONERA <br>
  Toulouse, France.
orcid: https://orcid.org/0000-0001-6261-8699
contact:
  (see my email address in my cv) <br>
  M2CI-DTIS, ONERA <br>
  2 Avenue Edouard Belin <br>
  31000 Toulouse, France.
bookmarks:
  <font size="+0.5"><a href="https://anfelopera.github.io/">Homepage</a></font> <br>
  <font size="+0.5"><a href="https://anfelopera.github.io/CV/">Curriculum Vitae</a></font> <br>
  <font size="+0.5"><a href="https://anfelopera.github.io/publications/">Publications</a></font> <br>
  <font size="+0.5"><a href="https://anfelopera.github.io/teaching/">Teaching</a></font> <br>
logo: personal/photoRound.png
gscholar: https://scholar.google.com.co/citations?user=RwmuQ1sAAAAJ&hl=en
researchgate: https://www.researchgate.net/profile/Andres_Lopez_Lopera
linkedin: https://fr.linkedin.com/in/andresflopezlopera?trk=public_profile_samename_mini-profile_title
section: CV
