theme: jekyll-theme-minimal
title: Andrés F. López-Lopera
description:
  Postdoctoral researcher <br>
  Toulouse Mathematics Institute <br>
  Toulouse, France.
orcid: https://orcid.org/0000-0001-6261-8699
contact:
  (see my email address in my cv) <br>
  BRGM, Office R14, Building D3 <br>
  3 avenue Claude-Guillemin <br>
  45060 Orléans Cedex 2, France.
bookmarks:
  <font size="+2"><a href="https://anfelopera.github.io/">Homepage</a></font> <br>
  <a href="https://anfelopera.github.io/CV/">Curriculum Vitae</a> <br>
  <a href="https://anfelopera.github.io/publications/">Publications</a> <br>
logo: personal/photoRound.png
gscholar: https://scholar.google.com.co/citations?user=RwmuQ1sAAAAJ&hl=en
researchgate: https://www.researchgate.net/profile/Andres_Lopez_Lopera
linkedin: https://fr.linkedin.com/in/andresflopezlopera?trk=public_profile_samename_mini-profile_title
section: CV
