theme: jekyll-theme-minimal
title: Andrés F. López-Lopera
description:
  Associate Professor, CERAMATHS <br>
  Univ. Polytechnique Hauts-de-France <br>
  59300 Valenciennes, France.
orcid: https://orcid.org/0000-0001-6261-8699
contact:
  andres{dot}lopezlopera{at}uphf{dot}fr
bookmarks:
  <font size="+0.5"><a href="https://anfelopera.github.io/">Homepage</a></font> <br>
  <font size="+0.5"><a href="https://anfelopera.github.io/funding/">Funding</a></font> <br>
  <font size="+0.5"><a href="https://anfelopera.github.io/publications/">Publications</a></font> <br>
  <font size="+0.5"><a href="https://anfelopera.github.io/toolboxes/">Toolboxes</a></font> <br>
  <font size="+0.5"><a href="https://anfelopera.github.io/supervision/">Supervision</a></font> <br>
  <font size="+0.5"><a href="https://anfelopera.github.io/teaching/">Teaching</a></font> <br>
logo: personal/photoRound.png
gscholar: https://scholar.google.com.co/citations?user=RwmuQ1sAAAAJ&hl=en
HAL : https://cv.archives-ouvertes.fr/anfelopera
researchgate: https://www.researchgate.net/profile/Andres_Lopez_Lopera
linkedin: https://fr.linkedin.com/in/andresflopezlopera?trk=public_profile_samename_mini-profile_title
section: CV
